version: "3"
services:
  edi-upload:
    build: .
    container_name: edi-upload
    ports:
        - 8089:8089
    environment:
      PORT: 8089
      EDI_DIR: "./EDI"
    volumes:
            - /usr/share/smartcerv/EDI:$EDI_DIR
