version: "3"
services:
  edi-upload:
    build: .
    container_name: edi-upload
    ports:
        - 8089:8089
    environment:
      PORT: $PORT
      EDI_DIR: $EDI_DIR
    volumes:
      - edi:$EDI_DIR
volumes:
  edi:
